### ISSUE TITLE
NameError: name 'driver' is not defined

### ISSUE THREAD

**Issue by jacksaturn** [jsetton/craigslist-renew#13]
Thank you for creating this script!

I have everything installed, but I'm receiving an error when I attempt to execute it:

```
Exception ignored in atexit callback: <function cleanup_session at 0x7f167c03d480>
Traceback (most recent call last):  
    File "craigslist-renew.py", line 227, in cleanup_session  
        if driver:  
NameError: name 'driver' is not defined
```

Any thoughts?

**Comment by jsetton** [comment]
How are you running the script?

**Comment by jacksaturn** [comment]
Yes, when I run the script, that's the message I receive.

Prior to that I was receiving an error message about fake_useragent, but it turned out that I didn't have fake_useragent installed. Once installed, I started receiving this error about 'driver'.

I attempted to omit the webdriver path in the logfile, but that didn't correct the error.

**Comment by jsetton** [comment]
Did you install all the required packages?

```sh
pip3 install -r requirements.txt
```

Keep in mind you will need to have a Selenium webdriver running on your machine for the script to work.

If not, I would suggest to use the [Docker image](https://hub.docker.com/r/jsetton/craigslist-renew).

**Comment by jsetton** [comment]
Actually I can replicate this issue on my end. I will look into it.

**Comment by jacksaturn** [comment]
Thank you, I appreciate it!

To answer your question, all required packages have been installed.

I also tried entering /usr/lib/chromium-browser/chromedriver as my webdriver path, but no change.

**Comment by jsetton** [comment]
You should have another error (most likely from the selenium webdriver) prior to the `driver` error.

**Comment by jacksaturn** [comment]
I'd overlooked the first one, but I see it now:

```
Something went wrong: exepected '<document start>', but found '<block mapping start>'
  in "config.yml", line 5, column 1
```

**Comment by jsetton** [comment]
> I'd overlooked the first one

The `driver` error is actually irrelevant. I will push a change to ignore it.

As far as being able replicate this error, I actually had an issue with my Selenium webdriver instance. Once fixed, the script worked fine.

So you should focus on the first error generated. It should be either an issue loading the configuration file or initializing the Selenium webdriver instance in this case.
