### ISSUE TITLE
Should this still work? It isn't for me.

### ISSUE THREAD

**Issue by a1ch3mist** [jsetton/craigslist-renew#23]
Should this code still work with python 3.12?

Installing modules completes OK.
When running it just exits, no log file created or error output.
Debugging makes it look like possibly it wants a config argument, but I'm specifying that argument as shown in the docs.

**Comment by jsetton** [comment]
It sounds like a configuration issue to me. Did you generate the config yaml file? What command did you run?

**Comment by a1ch3mist** [comment]
I edited the config.yml file and specify it in the path. I have chromedriver in path and also in the config file.

interesting - If I run it through VS Code debugger then it seems to work. But if I just run .\craigslist.renew.py .\config.yml it exits without log.

If I run python craigslist-renew.py it gives an error about no bs4 module.

Maybe better error logging output would help.

**Comment by jsetton** [comment]
> Maybe better error logging output would help.

There is a catch all exceptions wrapping the entire script implementation. If you aren't getting any errors, my guess is that the script ran as expected. As far as logs, if you are running in a terminal, any errors would be displayed along with being logged in the file specified in the config.

**Comment by jsetton** [comment]
Closing in favor of #24
