### ISSUE TITLE
NoSuchElementException - receiving this error often.

### ISSUE THREAD

**Issue by a1ch3mist** [jsetton/craigslist-renew#24]
I'm getting this error very often. The script may renew several items and then crash with one of these, apparently randomly. Re-running it may make some more progress:

Exception stacktrace:

Exception has occurred: NoSuchElementException
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type="submit" and @value="renew"]"}
  (Session info: chrome=128.0.6613.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6D7F7B632+29090]
	(No symbol) [0x00007FF6D7EEE6E9]
	(No symbol) [0x00007FF6D7DAB1CA]
	(No symbol) [0x00007FF6D7DFEFD7]
	(No symbol) [0x00007FF6D7DFF22C]
	(No symbol) [0x00007FF6D7E497F7]
	(No symbol) [0x00007FF6D7E2672F]
	(No symbol) [0x00007FF6D7E465D9]
	(No symbol) [0x00007FF6D7E26493]
	(No symbol) [0x00007FF6D7DF09B1]
	(No symbol) [0x00007FF6D7DF1B11]
	GetHandleVerifier [0x00007FF6D829883D+3294125]
	GetHandleVerifier [0x00007FF6D82E4423+3604371]
	GetHandleVerifier [0x00007FF6D82DA2E7+3563095]
	GetHandleVerifier [0x00007FF6D8036F16+797318]
	(No symbol) [0x00007FF6D7EF986F]
	(No symbol) [0x00007FF6D7EF5454]
	(No symbol) [0x00007FF6D7EF55E0]
	(No symbol) [0x00007FF6D7EE4A7F]
	BaseThreadInitThunk [0x00007FFEC2A5257D+29]
	RtlUserThreadStart [0x00007FFEC3CCAF28+40]
  File "C:\code\craigslist\craigslist-renew\craigslist-renew.py", line 71, in renew_posts
    button = driver.find_element(By.XPATH, '//input[@type="submit" and @value="renew"]')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\craigslist\craigslist-renew\craigslist-renew.py", line 264, in main
    renew_posts()
  File "C:\code\craigslist\craigslist-renew\craigslist-renew.py", line 274, in <module>
    main()
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type="submit" and @value="renew"]"}
  (Session info: chrome=128.0.6613.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6D7F7B632+29090]
	(No symbol) [0x00007FF6D7EEE6E9]
	(No symbol) [0x00007FF6D7DAB1CA]
	(No symbol) [0x00007FF6D7DFEFD7]
	(No symbol) [0x00007FF6D7DFF22C]
	(No symbol) [0x00007FF6D7E497F7]
	(No symbol) [0x00007FF6D7E2672F]
	(No symbol) [0x00007FF6D7E465D9]
	(No symbol) [0x00007FF6D7E26493]
	(No symbol) [0x00007FF6D7DF09B1]
	(No symbol) [0x00007FF6D7DF1B11]
	GetHandleVerifier [0x00007FF6D829883D+3294125]
	GetHandleVerifier [0x00007FF6D82E4423+3604371]
	GetHandleVerifier [0x00007FF6D82DA2E7+3563095]
	GetHandleVerifier [0x00007FF6D8036F16+797318]
	(No symbol) [0x00007FF6D7EF986F]
	(No symbol) [0x00007FF6D7EF5454]
	(No symbol) [0x00007FF6D7EF55E0]
	(No symbol) [0x00007FF6D7EE4A7F]
	BaseThreadInitThunk [0x00007FFEC2A5257D+29]
	RtlUserThreadStart [0x00007FFEC3CCAF28+40]

**Comment by jsetton** [comment]
How are you running the script? It seems like you are running some kind of debug mode. These exceptions are normal when there are no longer renew link available on a given page, and are actually caught by the `renew_posts` function.

**Comment by a1ch3mist** [comment]
In VS Code w/ Python extensions, under debugger.
It does renew some (random amount) and then errors often. Since it did not complete renewing, there are still renew links on the webpage so it should be able to find them.

I have noticed some unusual behavior on craigslist today though where it keeps shifting me between "most recent" and "active" when I complete a manual renew link. Perhaps this is confusing the script?

**Comment by jsetton** [comment]
> I have noticed some unusual behavior on craigslist today though where it keeps shifting me between "most recent" and "active" when I complete a manual renew link. Perhaps this is confusing the script?

It could be but if this is not normal behavior it is hard to say. Anyway, feel free to submit a PR if you are able to identify and correct the issue you seem to experience.
